[build]
functions = "functions"

[[redirects]]
    from="https://642d0627a678400008ed774e--illustrious-gingersnap-4de0b8.netlify.app/.netlify/functions/api/"
    to="/"
    status=200 
    force= true